getsentry/sentry-webpack-plugin

src/index.js
`this` had another context, I just save a new reference in the correct context.
Fixes #11
=> Fix options context

.gitignore, .travis.yml, README.md, __tests__/index.spec.js, package-lock.json, package.json, src/__tests__/index.spec.js, yarn.lock
=> test: Adding 100% coverage tests

README.md
* Add new `dryRun` option in README
* Link to example directory for reference
=> Add information about dry run

README.md, package-lock.json, package.json, src/__tests__/index.spec.js, src/index.js
Building upon pull-request by @couds #117
Solves #104
=> [Fix #104] Add silent option to disable all output to stdout

package-lock.json, package.json
Fixes: https://github.com/getsentry/sentry-webpack-plugin/issues/135
Actually, i'm having issues doing npm install of this package. Exit 1
=> fix(package.json): fixed cli crashing on install

index.d.ts
Fixes https://github.com/getsentry/sentry-webpack-plugin/issues/144
=> Fixed TS definitions export error

.snyk, package.json, yarn.lock
Fixes https://github.com/getsentry/sentry-webpack-plugin/issues/150
=> misc: Resolve snyk dependency issues

index.d.ts
=> chore: Fix setCommits types

README.md, package.json, src/index.js, yarn.lock
Closes https://github.com/getsentry/sentry-webpack-plugin/issues/184
=> feat: Allow to perform release deploys

src/index.js
related to https://github.com/getsentry/sentry-webpack-plugin/issues/205
=> fix(deploy): change newDeploy to deploy

README.md
=> ref(docs): README options edits

src/__tests__/index.spec.js, src/index.js
Fixes https://github.com/getsentry/sentry-webpack-plugin/issues/237
Ref https://github.com/getsentry/sentry-webpack-plugin/pull/240
=> feat: Add support for Webpack 5 entry descriptors

.npmignore
fixes https://github.com/getsentry/sentry-webpack-plugin/issues/247
=> build: Remove tests directory from npm release

README.md
=> Fix typo "filenamess"

src/__tests__/index.spec.js, src/index.js
=> feat: Use webpack output.path as defaullt include path

index.d.ts, package.json, src/index.js
ref: https://github.com/getsentry/sentry-cli/pull/999
*NOTE: Release only once `1.67.2` has been released*
=> Add missing ignoreEmpty option and cleanup TS typings

src/index.js
Fixes https://github.com/getsentry/sentry-webpack-plugin/issues/346
=> ref: Check if rawSource is available before use

package.json
Potential fix for https://github.com/getsentry/sentry-webpack-plugin/pull/343 cc @rchl
=> deps: Mark Webpack as optional peerDependency via peerDependenciesMeta

README.md
Fixes https://github.com/getsentry/sentry-docs/issues/6154
=> fix: Small Typo

README.md, example/webpack.config.js
Fixes https://github.com/getsentry/sentry-docs/issues/6202
=> chore: Make naming in readme consistent
