- README.md
- src/index.js
I need support for all source map options on SentryCLI so I added them: https://github.com/getsentry/sentry-cli/pull/182, now I need them in this plugin, that is the one I actually going to use.
Please let me know what is missing, probably other options need to be an array as well.
You can quickly debug it with these two files:
index.js
```
console.log('I AM INDEX!');
```
webpack.config.js
```
const SentryCliPlugin = require('./src/index.js');
module.exports = {
entry: './index.js',
output: {
filename: 'test.js'
},
plugins: [
new SentryCliPlugin({
release: 'sso',
include: 'test',
ignoreFile: 'seses',
urlPrefix: '~/context'
})
]
};
```
And running `webpack` (globally installed)
> feat: Add all source map options

- README.md
- package.json
- src/__tests__/index.spec.js
- src/index.js
- src/sentry-webpack.module.js
- src/sentry.loader.js
- yarn.lock
This is a breaking change, we no longer support compilation hash for now since this would conflict with code injection.
Basically what we do is, we inject 
```javascript
global.SENTRY_RELEASE={};
global.SENTRY_RELEASE.id="#MYHASH#";
```
into the webpack bundle.
<details>
<summary>Old comment</summary>
So I am not really happy with how this works right now.
I wasn't able to inject code during compilation into the source, how it's working now is:
Before compilation I add a fake module to the source containing
```javascript
global.SENTRY_RELEASE={};
global.SENTRY_RELEASE.id="";
```
After compilation I iterate over all chunks, and replace the corresponding code on the file system so the result in the compiled file is:
```javascript
global.SENTRY_RELEASE={}; …
```
> feat: Inject global.SENTRY_RELEASE.id into source

- README.md
Most of the description for `urlPrefix` looked like ~strike-through text~.
> Fix formatting issue in the README

- src/index.js
Fixes: https://github.com/getsentry/sentry-webpack-plugin/issues/28 and https://github.com/getsentry/sentry-webpack-plugin/issues/27
It's not deprecated and only "recommended" by official Webpack docs, so we should probably still support it - https://webpack.js.org/guides/migrating/#module-loaders-is-now-module-rules
> ref: Handle old module.loaders syntax

- src/index.js
webpack allows to configure the `entry` dynamic https://webpack.js.org/configuration/entry-context/#dynamic-entry.  
I added support for injecting the sentry entry also in dynamic entries, otherwise the plugin would output corrupt bundles.
> add support for dynamic entry 

- README.md
https://github.com/getsentry/sentry-cli/blob/d59bf19eab14b51d21b9ffdc3d41379b0dd4a16c/js/releases/options/uploadSourcemaps.js#L18-L21
> fix: Docs stripPrefix is an array

- package-lock.json
- src/__tests__/index.spec.js
- src/index.js
Webpack v4 uses new API for plugins to apply hooks. In this PR I used that new API if it is available.
> use webpack v4 new Tapable plugins hooks

- .prettierrc
- .travis.yml
- README.md
- jest.config.js
- package.json
- src/__tests__/index.spec.js
- src/index.js
- src/sentry.loader.js
- yarn.lock
This implements a feature request from #37 that allows to skip certain entry points via the `entry` option. The actual feature commit is 67901a7.
Since the code was not yet documented and test coverage was pretty low, I also refactored the whole thing and added more tests. It **should** now better live up to our usual coding standards. Test coverage is at nearly 100%, except for the dry-run CLI mock. 
Tests have been added for our modifications to the compiler options (namely `entry` and `module.rules`/`module.loaders`), which were previously untested. This should also make it easier to test certain webpack configurations, once we receive them from users.
> feat: Add an option to skip entries

- src/__tests__/index.spec.js
- src/index.js
Fixes https://github.com/getsentry/sentry-webpack-plugin/issues/36
> fix: Preserve original entries if they are not matching our filter

- README.md
Corrects the type (array) and usage (overrides instead of adds) of 'ext'.
Verified the actual behavior using v1.5.2 and sentry-cli v1.30.2.
> Correct description of 'ext' option

- README.md
- src/index.js
Resolves https://github.com/getsentry/sentry-webpack-plugin/issues/66
> Allow [hash] usage in release option

- README.md
Resolves https://github.com/getsentry/sentry-webpack-plugin/issues/65
Don't merge until we fix it in sentry-cli – https://github.com/getsentry/sentry-cli/pull/373/
> Adds urlSuffix option to the readme

- README.md
- src/index.js
I completely forgot that hash is available only after the loader compiled the module file we inject 🤦‍♂️ 
There's no need for a new release, as barely anyone uses this feature (it's only available <24h).
Ref: https://github.com/getsentry/sentry-webpack-plugin/issues/80
> Remove [hash] support

- src/sentry.loader.js
Accessing a global that doesn't exist crashes in node, we need to use `typeof x !== "undefined"`, this is what usually used to handle globals in different environments properly.
> Fix global check in loader

- src/index.js
Fix https://github.com/getsentry/sentry-webpack-plugin/issues/85
> fix: Extract loader name in more reliable way

- README.md
- src/__tests__/index.spec.js
- src/index.js
I am using on-premise version sentry on my workspace and it works amazingly except occasional build failure on CI server caused by a network issue.
#75, #100 and some more issues are complaining sentry error, and I guess they are suffered from a network limit like me. I cannot change my company's network policy, so, at least I need building my project with sentry release failure.
Sentry plugin is not a code processor and it does not directly affect the compiled code. It is plugin with side effect and IO, and there always is a possibility to fail regardless of the code itself. So, IMO it would be quite reasonable that users have the right to choose ignoring sentry plugin error.
I added `errorHandler` option. check-up, please?
> Add errorHandler option

- index.d.ts
- package.json
- yarn.lock
Hi!
I wanted to use this package in a TypeScript project and didn't any type definition file, so I made one.
Here is a PR if you're interested in including it in the package itself.
Cheers.
> chore(typescript): Add TypeScript definition file

- README.md
- src/__tests__/index.spec.js
- src/index.js
I added setCommits command to be able set associated commits through this plugin as requested here #71. Without this options you forced to use sentry-cli to set associated commits directly. Please check this out.
ToDo:
> feat: Add setCommits option

- README.md
Created markdown table for the options to make it a bit easier to read.
I left the set-commits part out due to #142. I will add it when #142 is concluded. (Either nested or not)
A lot of manual copy-pasting here, so I would appreciate if another pair of 👀 control-checked it 🌮 
<details>
<summary>Click me to preview table</summary>
Option | Type | Required | Description |
-------|------|----------|-------------
release | `string` | optional | unique name of a release, must be a `string`, should uniquely identify your release, defaults to `sentry-cli releases propose-version` command which should always return the correct version (**requires access to `git` CLI and root directory to be a valid repository**).
include | `string`/`array` | required | one or more paths that Sentry CLI should …
> [Suggestion] - Move options to markdown table

- README.md
- src/__tests__/index.spec.js
- src/index.js
After the **beautiful** work on the pr #139 finally got released, I implemented it to my org's codebase but in the process, I felt it was missing something:
The new options: ` commit, previousCommit, repo, auto` feels a bit polluting in the sentry-webpack-plugin's "global" options scope in my opinion. The key annoying me the most is `auto`.
`auto` has no context when seen like this:
```js
const sentryCliPlugin = new SentryCliPlugin({
release: '42',
auto: true,
});
```
My suggestion is to group the setCommits/git options in a object:
```js
const sentryCliPlugin = new SentryCliPlugin({
release: '42',
setCommits: {
auto: true,
//Other setCommits options here...
}
});
```
I modified the code in index.js to reflect this and tried to do the same in the tests. However, **the tests are not …
> [Suggestion] - Nested setCommits & readme fixes

- src/index.js
Currently, if you want this plugin to also attach commits, you need to specify both `auto: true` and `repo: 'whatever/repo'`.
When calling the cli with `--auto`, we don't need the repo name, and this PR fixes that.
Also see getsentry/sentry-cli#618
> Fix for commit requirement when release flag is set to auto

- README.md
- src/index.js
Fixes: https://github.com/getsentry/sentry-webpack-plugin/issues/148
> fix: Dont fail compilation if theres no release available

- README.md
- src/__tests__/index.spec.js
- src/index.js
Closes https://github.com/getsentry/sentry-webpack-plugin/issues/110
> feat: Allow for skiping release finalization

- src/index.js
updated index.js to ensure afterEmit hook exists because with current setup, it assume afterEmit hook exists (by checking if compiler.hooks).
> updated index.js to ensure afterEmit hook exists

- index.d.ts
Closes https://github.com/getsentry/sentry-webpack-plugin/issues/166
> chore: Update TS definitions

- src/index.js
This PR fixes a minor grammatical mistake in an error message.
`Unabled` ---> `Unable`
> chore: Fix error typo

- README.md
- index.d.ts
When "auto: true" then "repo" is optional.
Resolves #199
> fix(types): make setCommits.repo type optional

- index.d.ts
Adds types for deployment configuration introduced in #192
> fix(types): add deploy configuration to type definitions

- README.md
> Fix: Link to CLI configuration documentation

- src/__tests__/index.spec.js
- src/index.js
Without this programs will generally suppress the errors. I believe this is because they expect it to be an error object and they're reporting on `obj.message`.
> fix: Return an actual error for propagation

- index.d.ts
- src/index.js
This makes it possible to greatly simplify the user experience for customers trying to upload sourcemaps. We already install the sentry-cli via the npm package, but they were still required to setup a fairly cryptic configuration _in addition to_ also having to setup configuration in the plugin itself for various things. This ensures they can configure the entirety of the process within the webpack plugin.
Requires https://github.com/getsentry/sentry-cli/pull/830
> feat: Support minimal CLI options

- index.d.ts
```
interface WebpackPluginInstance extends Plugin {}
```
This interface `WebpackPluginInstance` was specifically created in Webpack 4 to fix such issues
// Compatibility with webpack@5's own types
// See https://github.com/webpack/webpack/issues/11630
> fix Webpack 5 types issue #258

- README.md
- index.d.ts
- src/index.js
When an artifact has a hash （example: `[contenthash]` on webpack）, it will be generated for each build.
Currently, we need to run the `delete` command with sentry-cli to clean the artifacts.
This is a PR that adds an option to allow the plugin to clean.
There is no command in sentry-cli that supports clean, so I'm running the clean command with `execute`.
I'm sorry if this PR shouldn't be the role of this plugin.
> feat: add `cleanAftifacts` option

- index.d.ts
- src/__tests__/index.spec.js
- src/index.js
Fixes https://github.com/getsentry/sentry-webpack-plugin/issues/269
This is an issue when using custom Gatsby webpack config and someone won't specify a `stage` in which plugin should be applied https://www.gatsbyjs.com/docs/how-to/custom-configuration/add-custom-webpack-config/ or when bundling serverless functions as individual artifacts https://www.serverless.com/framework/docs/providers/aws/guide/packaging/
> feat: Add runOnce flag to allow for skipping multiple uploads with the same config

- README.md
Per the description of [the underlying option in `sentry-cli`](https://github.com/getsentry/sentry-cli/blob/dfc380c8b4f95be5853b2b4f0abd2d0fbf1319ce/src/commands/releases.rs?plain=1#L314-L324) (and as borne out by manual testing), the `stripPrefix` option does _not_, in fact, influence the names of uploaded release artifacts.
> fix(docs): Fix description of `stripPrefix` option

- index.d.ts
We've been using `SentryCliUploadSourceMapsOptions`, but without actually having imported it. This fixes that.
> fix(types): Add missing `SentryCliUploadSourceMapsOptions` import

- package.json
This bumps our `@sentry/cli` dependency in order to take advantage of https://github.com/getsentry/sentry-cli/pull/1001. Once this change is released, it will unblock https://github.com/getsentry/sentry-javascript/pull/3845.
> chore(deps): Update @sentry/cli to 1.68

- README.md
Pulled from another PR, so as not to confuse things.
This also removes the link to Travis, since we no longer use it.
> chore(docs): Auto-format tables in README

- .github/workflows/release.yml
The release workflow here was relying on a very old version of `getsentry/action-prepare-release` but was referring to its `@main` branch and breaking due to major changes.
This PR brings the workflow up to speed with the recent version of it.
> ci(release): Fix release workflow

- index.d.ts
According to documentation in `readme.md`
> Fix types of SentryCliPluginOptions.errorHandler

- yarn.lock
This was missed as part of https://github.com/getsentry/sentry-webpack-plugin/pull/297.
> chore(deps): Update `yarn.lock` for `@sentry/cli`

- index.d.ts
The `SentryCliPlugin` class has a public property called `options`, but it's not in the type, so TS gets mad when you try to access it.
> fix(types): Add `options` to main plugin type

- .github/workflows/ci.yml
- index.d.ts
- package.json
- src/cjs.js
- yarn.lock
Because the webpack plugin is written in vanilla JS (rather than TS), we have a manually-generated type declaration file, where we default-export the `SentryCliPlugin` class. We also have a file (`cjs.js`) which is meant to make the plugin play nicely with CommonJS imports. And if the user is indeed using CommonJS imports (`const SentryWebpackPlugin = require('@sentry/webpack-plugin')`), that all works great.
But if you try to do ES6 imports, the only form which gets you anything besides `undefined` is `import * as SentryWebpackPlugin from '@sentry/webpack-plugin`.* As far as TS is concerned, though, that creates a namespace rather than a class, and so it will refuse to let you call `new SentryWebpackPlugin`, instead telling you that `SentryWebpackPlugin` is not contructable. One solution …
> fix(types): Enable plugin to be imported under ES6

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
By default, node limits stacktraces to 10 lines. That's often not enough to tell what's gone wrong, especially when dealing with async code (which can add many frames just handling its own asynciness). For example, when trying to release this plugin, I ran into this:
What's wrong? How do I fix it? No way to know.
Fortunately, node allows you to increase that limit, and since version 8, has further allowed you to specify global options via the `NODE_OPTIONS` environment variable. This PR does both, for all ci processes where we own the code that's being run.
Before:
After:
> fix(ci): Increase stack size in errors

- example/test.js
- example/webpack.config.js
- src/index.js
- src/sentry.loader.js
this is a recreated/clean version of https://github.com/getsentry/sentry-webpack-plugin/pull/291
I had to disable a few es-lint rules;
- index.js line 82-83: adding webpack-sources as dependency breaks the tests (some of the tests use older version(s) of node than webpack-sources requires as minimum). On the other hand, if the user is using module federation, their webpack version is at least 5 and webpack-sources come with it. So, adding webpack-sources as a dependency is not a must. For the same reason, I did not put the require statement at the top of the file (it might be missing for users using an older version of webpack)
- index js line 105; it is what it is, the rule says no-underscore-dangle but the object coming from webpack has it 🤷🏼‍♂️
----
TL;DR;
the plugin now injects …
> add support for multiple apps using module federation

- package.json
add webpack as peerDependency as webpack is used in index.d.ts for typing
https://github.com/getsentry/sentry-webpack-plugin/blob/4e85f797a4b9736c7d52e99c30c5dd933f3b4c3e/index.d.ts#L1
> deps: add missing peerDep

- .craft.yml
So that I can maintain commits list as our changelog and make releases without redundant "added changelog" PRs.
https://github.com/getsentry/craft#changelog-policies
> ci: Change changelogPolicy to auto for Craft releases

- CHANGELOG.md
My quote was misplaced due to `auto` changelog policy picking up old entry.
> misc: Correct 1.18.6 changelog

- README.md
- package.json
After discussing it with the team, we decided to revert this change, as the behavior of `peerDependenciesMeta` is not consistent across npm/yarn versions.
ref: https://github.com/getsentry/sentry-webpack-plugin/pull/343
ref: https://github.com/getsentry/sentry-webpack-plugin/pull/350
> deps: Remove webpack from peerDep and move info about ver to readme

- package.json
- yarn.lock
```
feat: Add checksum validation for installed binaries (set SENTRYCLI_SKIP_CHECKSUM_VALIDATION to opt-out) (#1123)
feat: Use default xcode values for plist struct (#1111)
fix: Detect unwind and debug information in files linked with gold (#1124)
fix: Dont include debug_id during assemble when not PDBs are not supported (#1110)
fix: Fixes a panic when inspecting debug files larger than 4GB (#1117)
ref: Remove all release files instantaneously with --all flag (#1108)
ref: Silence progress bar in CI environments by default (#1122)
ref: Update log message when bundle ID is missing (#1113)
```
> deps: Bump sentry-cli to 1.73.0

- package.json
- yarn.lock
update @sentry/cli to latest major version
because new users to @sentry/cli will be pulling that major version and if they also use the plugin they'll now have two versions installed - it is probably not an issue but it is damn confusing to have two major versions in the yarn.lock file
> chore: update @sentry/cli to latest major version

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
- package.json
- yarn.lock
99% of changes are automatic formatting changes. Only relevant change is bumping `@sentry/cli` from `1.74.3` to `1.74.4`
> ref: Update sentry-cli and refresh GH actions

- package.json
- src/index.js
- yarn.lock
In https://github.com/getsentry/sentry-webpack-plugin/pull/307, a dependency on `webpack-sources` was added to the code, but not to `package.json`. From that PR description:
> Adding webpack-sources as dependency breaks the tests (some of the tests use older version(s) of node than webpack-sources requires as minimum). On the other hand, if the user is using module federation, their webpack version is at least 5 and webpack-sources come with it. So, adding webpack-sources as a dependency is not a must. For the same reason, I did not put the require statement at the top of the file (it might be missing for users using an older version of webpack)
Though this logic is generally sound, it (specifically the "their webpack version is at least 5 and webpack-sources come with it" part) doesn't …
> fix(deps): Add `webpack-sources` dependency

- src/index.js
This PR set the `SENTRY_PIPELINE` env variable so we can set the user agent here: https://github.com/getsentry/sentry-cli/blob/6f9173687fdfd56810145c5c727ff76978784814/src/api.rs
This approach was taken from Github actions: https://github.com/getsentry/action-release/blob/master/src/cli.ts#L13
> feat: adds pipeline argument

- index.d.ts
- src/index.js
It would be great if downstream consumers of the webpack plugin could check if the binary has successfully downloaded
Ref: https://github.com/getsentry/sentry-javascript/pull/6015
> feat: Add a means to detect if the CLI binary exists

- package.json
- yarn.lock
This PR bumps the version of the `@sentry/cli` dependency to have the upsides of https://github.com/getsentry/sentry-cli/pull/1375.
> build: Bump `@sentry/cli` version to `1.74.6`

- .github/workflows/build.yml
Committed via https://github.com/asottile/all-repos
> ci: Update actions/upload-artifact to v3.1.1

- example/package.json
- package.json
- yarn.lock
[1.75.0](https://github.com/getsentry/sentry-cli/releases/tag/1.75.0) should fix the ansi-regex security warning.
> fix: Update @sentry/cli to 1.75.0 to fix ansi-regex security warning

- CHANGELOG.md
`##Unreleased` is intentional because the `changelogPolicy` is `auto`
> meta: Update Changelog for 1.20.1
